version: '3.4'

networks:
  backend:

services:
  customerdb:
    container_name: customer-db
    image:  mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=password@12345#
    networks:
        - backend
    ports:
        - 18001:1433

  customerapi:
    container_name: customer-api
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: CustomerAPI/Dockerfile
    networks:
     - backend
    environment:
     - DB_HOST=customerdb
     - DB_NAME=customer_orm
     - MSSQL_SA_PASSWORD=password@12345#


  productdb:
   container_name: product-db
   image: mysql:8.0.29-oracle
   environment :
   - MYSQL_ROOT_PASSWORD=123456
   ports:
   - 18003:3306
   networks:
   - backend


  productapi:
    container_name: product-api
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: ProductAPI/Dockerfile
    networks:
     - backend
    environment:
     - DB_HOST=productdb
     - DB_NAME=product_orm
     - DB_ROOT_PASSWORD=123456


  orderdb:
    container_name: order-db
    image: mongo
    ports:
     - 18005:27017
    networks:
     - backend




 

  orderapi:
    container_name: order-api
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: OrderAPI/Dockerfile
    networks:
     - backend
    environment:
     - DB_HOST=orderdb
     - DB_NAME=order_orm

